### ISSUE TITLE
Effeciently applying CSS Styles

### ISSUE THREAD

**Issue by reviewer99** [vmoore12/prj-rev-bwfs-dasmoto#4]
When writing your CSS styles it is best to try and eliminate any duplicate styles found in your stylesheet as it makes it easier to make changes in the future.

For example here instead of the following:
```CSS
#brush {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: mediumspringgreen;

}

#frame {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: lightcoral;
}

#paint {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: skyblue;
}
```

You could have done something like this:
```CSS
h2 {
  font-family: "Helvetica";
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

This way all your `h2`s inherit the styles they all share and you only need to apply the unique background they all have.

You can even go another step further and eliminate the need to specify the font family on all your elements by applying a global rule on the body of the document like:
```CSS
body {
  font-family: "Helvetica";
}
```

With the rule above all your elements will inherit the specified font family

https://github.com/vmoore12/prj-rev-bwfs-dasmoto/blob/ac0f58f08bcc4b411176d9b3626ed27aacd6d945/DasmotosArtsCraft/resources/style.css#L10-L33
